-- CREATE DATABASE IF NOT EXISTS my_blog CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE my_blog;

-- CREATE TABLE users (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(80) NOT NULL,
--   email VARCHAR(190) NOT NULL UNIQUE,
--   password_hash VARCHAR(255) NOT NULL,
--   role ENUM('user','admin') NOT NULL DEFAULT 'user',
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE posts (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   user_id INT NOT NULL,
--   title VARCHAR(200) NOT NULL,
--   slug VARCHAR(220) NOT NULL UNIQUE,
--   body MEDIUMTEXT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );

-- CREATE TABLE comments (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   post_id INT NOT NULL,
--   user_id INT NULL,
--   author_name VARCHAR(80) NULL,
--   author_email VARCHAR(190) NULL,
--   body TEXT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
--   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
-- );
